In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df=pd.read_csv("E:\\COURSE\\data.csv")

In [3]:
df.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0

In [4]:
df.tail()

Age  Gender Education Level                      Job Title  \
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0

In [5]:
abc=df.dropna()

In [14]:
from sklearn.preprocessing import OrdinalEncoder
en1=OrdinalEncoder()
abc[["Gender","Education Level","Job Title"]]=en1.fit_transform(abc[["Gender","Education Level","Job Title"]])

C:\Users\Subash\AppData\Local\Temp\ipykernel_7248\2198333061.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abc[["Gender","Education Level","Job Title"]]=en1.fit_transform(abc[["Gender","Education Level","Job Title"]])


In [15]:
abc

Age  Gender  Education Level  Job Title  Years of Experience    Salary
0    32.0     1.0              0.0      159.0                  5.0   90000.0
1    28.0     0.0              1.0       17.0                  3.0   65000.0
2    45.0     1.0              2.0      130.0                 15.0  150000.0
3    36.0     0.0              0.0      101.0                  7.0   60000.0
4    52.0     1.0              1.0       22.0                 20.0  200000.0
..    ...     ...              ...        ...                  ...       ...
370  35.0     0.0              0.0      131.0                  8.0   85000.0
371  43.0     1.0              1.0       30.0                 19.0  170000.0
372  29.0     0.0              0.0       70.0                  2.0   40000.0
373  34.0     1.0              0.0      137.0                  7.0   90000.0
374  44.0     0.0              2.0      110.0                 15.0  150000.0

[373 rows x 6 columns]

In [149]:
one.categories_

[array([0., 1., 2.])]

In [150]:
x=abc.drop(["Age","Gender","Job Title","Salary"],axis='columns').values

In [34]:
x=abc.iloc[:,:4].values

In [35]:
x

array([[ 32.,   1.,   0., 159.],
       [ 28.,   0.,   1.,  17.],
       [ 45.,   1.,   2., 130.],
       ...,
       [ 29.,   0.,   0.,  70.],
       [ 34.,   1.,   0., 137.],
       [ 44.,   0.,   2., 110.]])

In [32]:
y=abc.iloc[:,-1].values

In [33]:
y

array([ 90000.,  65000., 150000.,  60000., 200000.,  55000., 120000.,
        80000.,  45000., 110000.,  75000., 140000.,  65000., 130000.,
        40000., 125000.,  90000., 115000.,  35000., 180000.,  80000.,
       190000.,  50000.,  60000., 140000.,  45000., 110000.,  40000.,
       140000.,  90000., 250000.,  55000.,  75000.,  65000., 170000.,
        45000.,  60000., 115000.,  40000., 160000.,  80000., 190000.,
        60000.,  45000., 130000.,  40000.,  75000., 180000., 120000.,
        35000., 130000.,  85000.,  60000., 200000.,  50000.,  95000.,
        65000., 140000.,  55000., 105000., 170000.,  50000.,  80000.,
       180000.,  35000.,  90000., 120000.,  45000.,  90000., 150000.,
        65000.,  70000., 190000.,  40000., 120000.,  95000., 160000.,
       100000., 180000.,  55000.,  70000.,  80000.,  30000., 250000.,
        40000.,  95000.,  45000.,  80000., 135000.,  55000., 120000.,
        40000., 105000., 170000.,  75000.,  65000., 160000.,  35000.,
        90000., 1100

In [66]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [73]:
x_train.shape

(261, 4)

In [76]:
y_train.shape

(261,)

In [74]:
x_test.shape

(112, 4)

In [75]:
y_test.shape

(112,)

In [67]:
from sklearn.linear_model import LinearRegression
feet=LinearRegression()
feet.fit(x_train,y_train)

LinearRegression()

In [68]:
#predict
y_pred=feet.predict(x_test)

In [60]:
y_test

array([ 40000.,  40000.,  50000., 140000.,  85000., 140000.,  60000.,
       115000.,  40000., 190000.,  70000., 130000., 150000., 105000.,
       120000.,  60000.,  45000.,  40000., 150000., 180000.,  90000.,
        95000., 120000.,  40000., 170000.,  40000.,  45000.,  50000.,
       120000.,  65000.,  70000., 100000., 100000., 120000.,  45000.,
       130000.,  75000., 110000.,  90000.,  60000., 120000., 150000.,
       125000., 180000., 170000.,  55000.,  55000., 105000.,  80000.,
        90000., 120000.,  95000., 100000.,  95000.,  80000., 180000.,
        90000.,  40000.,  40000.,  50000.,  45000., 160000., 150000.,
        40000.,  35000.,  95000.,  95000., 170000.,  50000., 150000.,
        65000.,  45000., 110000.,  35000., 180000.,  50000.,  50000.,
        85000., 180000.,  55000.,  55000.,  80000.,  40000.,  40000.,
        35000., 190000.,  95000.,  45000.,  35000.,  50000.,  45000.,
        50000.,  50000., 155000.,  40000., 170000.,  50000., 100000.,
       180000., 1100

In [41]:
x_test

array([[ 28.,   0.,   0.,  10.],
       [ 30.,   1.,   0.,  49.],
       [ 29.,   0.,   0.,  38.],
       [ 45.,   1.,   1., 152.],
       [ 35.,   0.,   0., 131.],
       [ 44.,   0.,   2., 150.],
       [ 32.,   0.,   0.,  64.],
       [ 42.,   1.,   1.,  95.],
       [ 28.,   1.,   0.,  49.],
       [ 51.,   0.,   1.,  28.],
       [ 33.,   0.,   0.,  66.],
       [ 40.,   1.,   0., 118.],
       [ 44.,   0.,   2., 139.],
       [ 35.,   1.,   1.,  93.],
       [ 36.,   1.,   2.,  91.],
       [ 33.,   1.,   0.,  49.],
       [ 30.,   1.,   0.,  65.],
       [ 28.,   1.,   0.,  50.],
       [ 42.,   0.,   2., 115.],
       [ 50.,   0.,   1.,  25.],
       [ 34.,   1.,   0., 110.],
       [ 36.,   1.,   0., 135.],
       [ 39.,   1.,   0., 135.],
       [ 29.,   0.,   0.,  70.],
       [ 51.,   0.,   1.,  30.],
       [ 30.,   0.,   0.,  60.],
       [ 31.,   0.,   0.,  34.],
       [ 33.,   1.,   0.,  76.],
       [ 42.,   0.,   1.,  93.],
       [ 28.,   0.,   1.,  17.],
       [ 3

In [88]:
feet_data=feet.predict([[29,1,2,150]])

In [89]:
feet_data

array([85334.01571948])

In [84]:
feet_data2=feet.score(x_train, y_train)

In [85]:
print("Train score:",feet.score( x_train,y_train))
print("Test score:",feet.score(x_test,y_test))

Train score: 0.8768598752509973
Test score: 0.9271832852957753
